#!/bin/zsh
# Xcode Cloud: MeowDisplay.xcodeproj is generated by XcodeGen and not
# committed, so install XcodeGen and generate it from project.yml after clone.
set -euo pipefail

brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"
DEVELOPMENT_TEAM="${CI_TEAM_ID:-}" xcodegen generate
